set nocompatible              " be iMproved, required
filetype off                  " required
let base16colorspace=256  " Access colors present in 256 colorspace
imap <C-c> <CR><Esc>O
set expandtab
set shiftwidth=2
set softtabstop=2
set number
set paste
set background=dark
syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Set theme
Plugin 'chriskempson/base16-vim'

" My Bundles here:
Plugin 'kien/ctrlp.vim'
Plugin 'gcmt/wildfire.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'Shougo/neosnippet.vim'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'nathanaelkane/vim-indent-guides'

" Syntax highlighters
Plugin 'tpope/vim-markdown'
Plugin 'hdima/python-syntax'
Plugin 'groenewege/vim-less'
Plugin 'slava/vim-spacebars'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'pangloss/vim-javascript'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leafgarland/typescript-vim'
Plugin 'mustache/vim-mustache-handlebars'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
